### ISSUE TITLE
JLD load() crashes on windows

### ISSUE THREAD

**Issue by igorcerovsky** [JuliaIO/JLD.jl#105] opened 2016-11-08 13:14 UTC
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffe3661c409 -- RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
while loading no file, in expression starting on line 0
RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
free at C:\WINDOWS\System32\msvcrt.dll (unknown line)
h5t_get_member_name at C:\Users\Igor Cerovsky\.julia\v0.5\HDF5\src\plain.jl:2188
jldatatype at C:\Users\Igor Cerovsky\.julia\v0.5\JLD\src\jld_types.jl:735
read at C:\Users\Igor Cerovsky\.julia\v0.5\JLD\src\JLD.jl:390
unknown function (ip: 0000000020F70A66)
read at C:\Users\Igor Cerovsky\.julia\v0.5\JLD\src\JLD.jl:366
collect at .\array.jl:307
#37 at C:\Users\Igor Cerovsky\.julia\v0.5\JLD\src\JLD.jl:1224
unknown function (ip: 0000000020F6F116)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
#jldopen#11 at C:\Users\Igor Cerovsky\.julia\v0.5\JLD\src\JLD.jl:265
load at C:\Users\Igor Cerovsky\.julia\v0.5\JLD\src\JLD.jl:1223
unknown function (ip: 0000000020F6E836)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
#load#13 at C:\Users\Igor Cerovsky\.julia\v0.5\FileIO\src\loadsave.jl:45
load at C:\Users\Igor Cerovsky\.julia\v0.5\FileIO\src\loadsave.jl:45
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
do_call at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:66
eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:190
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:558 [inlined]
jl_toplevel_eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:580
jl_toplevel_eval_in_warn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:590
eval at .\boot.jl:234
unknown function (ip: 0000000061C4D605)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
eval_user_input at .\REPL.jl:64
unknown function (ip: 0000000020F3A0CA)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
macro expansion at .\REPL.jl:95 [inlined]
#3 at .\event.jl:68
unknown function (ip: 0000000020F31073)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1392 [inlined]
start_task at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:253
Allocations: 4529332 (Pool: 4528282; Big: 1050); GC: 6

**Comment by simonster** [comment] 2016-11-08 14:32
Duplicate of #103.

**Closed by simonster** 2016-11-08 14:32 UTC
